/****************************************************************************************************
* FileName:   	   pmbus_command.h
* Processor:       dsPIC33CK
* Compiler:        XC16 V1.41
* Programmer(s):   Nick Huang
* Description:     Source file for Barracuda 4
****************************************************************************************************/
#ifndef __PMBUS_COMMAND_H
#define __PMBUS_COMMAND_H
#include "Switchs.h"
#include "types.h"

/*--------------------------------------------------
     Command Codes
--------------------------------------------------*/
//#define CMD_RESERVED_00                                   0x00
#define CMD_OPERATION                                       0x01
#define CMD_ON_OFF_CONFIG                                   0x02
#define CMD_CLEAR_FAULTS                                    0x03
//#define CMD_RESERVED_04                                   0x04
//#define CMD_RESERVED_05                                   0x05
//#define CMD_RESERVED_06                                   0x06
//#define CMD_RESERVED_07                                   0x07
//#define CMD_RESERVED_08                                   0x08
//#define CMD_RESERVED_09                                   0x09
//#define CMD_RESERVED_0A                                   0x0A
//#define CMD_RESERVED_0B                                   0x0B
//#define CMD_RESERVED_0C                                   0x0C
//#define CMD_RESERVED_0D                                   0x0D
//#define CMD_RESERVED_0E                                   0x0E
//#define CMD_RESERVED_0F                                   0x0F
#define CMD_BOOT_PROTECT                                    0x10
#define CMD_STORE_DEFAULT_ALL                               0x11
#define CMD_RESTORE_DEFAULT_ALL                             0x12
//#define CMD_RESERVED_13                                   0x13
//#define CMD_RESERVED_14                                   0x14
//#define CMD_RESERVED_15                                   0x15
//#define CMD_RESERVED_16                                   0x16
//#define CMD_RESERVED_17                                   0x17
//#define CMD_RESERVED_18                                   0x18
#define CMD_CAPABILITY                                      0x19
//#define CMD_RESERVED_1A                                   0x1A
//#define CMD_RESERVED_1B                                   0x1B
//#define CMD_RESERVED_1C                                   0x1C
//#define CMD_RESERVED_1D                                   0x1D
//#define CMD_RESERVED_1E                                   0x1E
//#define CMD_RESERVED_1F                                   0x1F
#define CMD_VOUT_MODE                                       0x20
#define CMD_VOUT_COMMAND                                    0x21
//#define CMD_RESERVED_22                                   0x22
#define CMD_VOUT_CAL_OFFSET                                 0x23
//#define CMD_RESERVED_24                                   0x24
#define CMD_VOUT_MARGIN_HIGH                                0x25
#define CMD_VOUT_MARGIN_LOW                                 0x26
//#define CMD_RESERVED_27                                   0x27
#define CMD_VOUT_DROOP                                      0x28
//#define CMD_RESERVED_29                                   0x29
//#define CMD_RESERVED_2A                                   0x2A
//#define CMD_RESERVED_2B                                   0x2B
//#define CMD_RESERVED_2C                                   0x2C
//#define CMD_RESERVED_2D                                   0x2D
//#define CMD_RESERVED_2E                                   0x2E
//#define CMD_RESERVED_2F                                   0x2F
//#define CMD_RESERVED_30                                   0x30
//#define CMD_RESERVED_31                                   0x31
//#define CMD_RESERVED_32                                   0x32
//#define CMD_RESERVED_33                                   0x33
//#define CMD_RESERVED_34                                   0x34
#define CMD_VIN_ON                                          0x35
#define CMD_VIN_OFF                                         0x36
//#define CMD_RESERVED_37                                   0x37
//#define CMD_RESERVED_38                                   0x38
//#define CMD_RESERVED_39                                   0x39
//#define CMD_RESERVED_3A                                   0x3A
//#define CMD_RESERVED_3B                                   0x3B
//#define CMD_RESERVED_3C                                   0x3C
//#define CMD_RESERVED_3D                                   0x3D
//#define CMD_RESERVED_3E                                   0x3E
//#define CMD_RESERVED_3F                                   0x3F
#define CMD_VOUT_OV_FAULT_LIMIT                             0x40
#define CMD_VOUT_OV_FAULT_RESPONSE                          0x41
//#define CMD_RESERVED_42                                   0x42
//#define CMD_RESERVED_43                                   0x43
//#define CMD_RESERVED_44                                   0x44
//#define CMD_RESERVED_45                                   0x45
#define CMD_IOUT_OC_FAULT_LIMIT                             0x46
#define CMD_IOUT_OC_FAULT_RESPONSE                          0x47
//#define CMD_RESERVED_48                                   0x48
//#define CMD_RESERVED_49                                   0x49
#define CMD_IOUT_OC_WARN_LIMIT                              0x4A
//#define CMD_RESERVED_4B                                   0x4B
//#define CMD_RESERVED_4C                                   0x4C
//#define CMD_RESERVED_4D                                   0x4D
//#define CMD_RESERVED_4E                                   0x4E
#define CMD_OT_FAULT_LIMIT                                  0x4F
#define CMD_OT_FAULT_RESPONSE                               0x50
#define CMD_OT_WARN_LIMIT                                   0x51
//#define CMD_RESERVED_52                                   0x52
//#define CMD_RESERVED_53                                   0x53
//#define CMD_RESERVED_54                                   0x54
#define CMD_VIN_OV_FAULT_LIMIT                              0x55
#define CMD_VIN_OV_FAULT_RESPONSE                           0x56
//#define CMD_RESERVED_57                                   0x57
//#define CMD_RESERVED_58                                   0x58
//#define CMD_RESERVED_59                                   0x59
//#define CMD_RESERVED_5A                                   0x5A
//#define CMD_RESERVED_5B                                   0x5B
//#define CMD_RESERVED_5C                                   0x5C
//#define CMD_RESERVED_5D                                   0x5D
#define CMD_POWER_GOOD_ON                                   0x5E
#define CMD_POWER_GOOD_OFF                                  0x5F
#define CMD_TON_DELAY                                       0x60
#define CMD_TON_RISE                                        0x61
//#define CMD_RESERVED_62                                   0x62
//#define CMD_RESERVED_63                                   0x63
//#define CMD_RESERVED_64                                   0x64
//#define CMD_RESERVED_65                                   0x65
//#define CMD_RESERVED_66                                   0x66
//#define CMD_RESERVED_67                                   0x67
//#define CMD_RESERVED_68                                   0x68
//#define CMD_RESERVED_69                                   0x69
//#define CMD_RESERVED_6A                                   0x6A
//#define CMD_RESERVED_6B                                   0x6B
//#define CMD_RESERVED_6C                                   0x6C
//#define CMD_RESERVED_6D                                   0x6D
//#define CMD_RESERVED_6E                                   0x6E
//#define CMD_RESERVED_6F                                   0x6F
//#define CMD_RESERVED_70                                   0x70
//#define CMD_RESERVED_71                                   0x71
//#define CMD_RESERVED_72                                   0x72
//#define CMD_RESERVED_73                                   0x73
//#define CMD_RESERVED_74                                   0x74
//#define CMD_RESERVED_75                                   0x75
//#define CMD_RESERVED_76                                   0x76
//#define CMD_RESERVED_77                                   0x77
//#define CMD_RESERVED_78                                   0x78
#define CMD_STATUS_WORD                                     0x79
#define CMD_STATUS_VOUT                                     0x7A
#define CMD_STATUS_IOUT                                     0x7B
#define CMD_STATUS_INPUT                                    0x7C
#define CMD_STATUS_TEMP1                                    0x7D
#define CMD_STATUS_CML                                      0x7E
//#define CMD_RESERVED_7F                                   0x7F
//#define CMD_RESERVED_70                                   0x80
//#define CMD_RESERVED_81                                   0x81
//#define CMD_RESERVED_82                                   0x82
//#define CMD_RESERVED_83                                   0x83
//#define CMD_RESERVED_84                                   0x84
//#define CMD_RESERVED_85                                   0x85
//#define CMD_RESERVED_86                                   0x86
//#define CMD_RESERVED_87                                   0x87
#define CMD_READ_VIN                                        0x88
//#define CMD_RESERVED_8                                    0x89
//#define CMD_RESERVED_8                                    0x8A
#define CMD_READ_VOUT                                       0x8B
#define CMD_READ_IOUT                                       0x8C
#define CMD_READ_TEMP1                                      0x8D
#define CMD_READ_TEMP2                                      0x8E
#define CMD_READ_VOUT_I                                     0x8F
//#define CMD_RESERVED_90                                   0x90
//#define CMD_RESERVED_91                                   0x91
//#define CMD_RESERVED_92                                   0x92
//#define CMD_RESERVED_93                                   0x93
//#define CMD_RESERVED_94                                   0x94
//#define CMD_RESERVED_95                                   0x95
//#define CMD_RESERVED_96                                   0x96
//#define CMD_RESERVED_97                                   0x97
#define CMD_PMBUS_REVISION                                  0x98
//#define CMD_RESERVED_99                                   0x99
#define CMD_MFR_MODEL                                       0x9A
//#define CMD_RESERVED_9B                                   0x9B
//#define CMD_RESERVED_9C                                   0x9C
//#define CMD_RESERVED_9D                                   0x9D
#define CMD_MFR_SERIAL                                      0x9E
//#define CMD_RESERVED_9F                                   0x9F
//#define CMD_RESERVED_A0                                   0xA0
//#define CMD_RESERVED_A1                                   0xA1
//#define CMD_RESERVED_A2                                   0xA2
//#define CMD_RESERVED_A3                                   0xA3
//#define CMD_RESERVED_A4                                   0xA4
//#define CMD_RESERVED_A5                                   0xA5
//#define CMD_RESERVED_A6                                   0xA6
//#define CMD_RESERVED_A7                                   0xA7
//#define CMD_RESERVED_A8                                   0xA8
//#define CMD_RESERVED_A9                                   0xA9
//#define CMD_RESERVED_AA                                   0xAA
//#define CMD_RESERVED_AB                                   0xAB
//#define CMD_RESERVED_AC                                   0xAC
//#define CMD_RESERVED_AD                                   0xAD
//#define CMD_RESERVED_AE                                   0xAE
//#define CMD_RESERVED_AF                                   0xAF
//#define CMD_RESERVED_B0                                   0xB0
//#define CMD_RESERVED_B1                                   0xB1
//#define CMD_RESERVED_B2                                   0xB2
//#define CMD_RESERVED_B3                                   0xB3
//#define CMD_RESERVED_B4                                   0xB4
//#define CMD_RESERVED_B5                                   0xB5
//#define CMD_RESERVED_B6                                   0xB6
//#define CMD_RESERVED_B7                                   0xB7
//#define CMD_RESERVED_B8                                   0xB8
//#define CMD_RESERVED_B9                                   0xB9
//#define CMD_RESERVED_BA                                   0xBA
//#define CMD_RESERVED_BB                                   0xBB
//#define CMD_RESERVED_BC                                   0xBC
//#define CMD_RESERVED_BD                                   0xBD
//#define CMD_RESERVED_BE                                   0xBE
//#define CMD_RESERVED_BF                                   0xBF
//#define CMD_RESERVED_C0                                   0xC0
//#define CMD_RESERVED_C1                                   0xC1
//#define CMD_RESERVED_C2                                   0xC2
//#define CMD_RESERVED_C3                                   0xC3
//#define CMD_RESERVED_C4                                   0xC4
//#define CMD_RESERVED_C5                                   0xC5
//#define CMD_RESERVED_C6                                   0xC6
//#define CMD_RESERVED_C7                                   0xC7
//#define CMD_RESERVED_C8                                   0xC8
//#define CMD_RESERVED_C9                                   0xC9
//#define CMD_RESERVED_CA                                   0xCA
//#define CMD_RESERVED_CB                                   0xCB
//#define CMD_RESERVED_CC                                   0xCC
//#define CMD_RESERVED_CD                                   0xCD
//#define CMD_RESERVED_CE                                   0xCE
//#define CMD_RESERVED_CF                                   0xCF
#define CMD_MFR_DEVICE_TYPE                                 0xD0
#define CMD_MFR_VOUT_READ_CAL_GAIN                          0xD1
#define CMD_MFR_VOUT_READ_CAL_OFF                           0xD2
#define CMD_MFR_VIN_READ_CAL_GAIN                           0xD3	
#define CMD_MFR_VIN_READ_CAL_OFF                            0xD4
//#define CMD_MFR_RESERVED_D5                               0xD5
#define CMD_MFR_IOUT_CAL_GAIN                               0xD6
#define CMD_MFR_IOUT_CAL_OFFSET                             0xD7
#define MFR_CMD_BOOT_PWD                                    0xD8
#define MFR_CMD_BOOT_MODE                                   0xD9
//#define CMD_MFR_RESERVED_DA                               0xDA
#define CMD_MFR_FW_REV                                      0xDB
#define MFR_CAL_SW_ON_COMMAND                               0xDC
#define MFR_CAL_SW_OFF_COMMAND                              0xDD
//#define CMD_MFR_RESERVED_DE                               0xDE
#define MFR_RESTORE_FACTORY_DFLTS                           0xDF

#define CMD_PASSWORD_W                                      0xE0
#define CMD_TARGETS_LIST_R                                  0xE1
#define CMD_WHO_AM_I_RW                                     0xE2
#define CMD_MFR_SW_VER                                      0xE3
#define CMD_MEMORY_INFO_R                                   0xE4
#define CMD_APP_STATUS_R                                    0xE5
#define CMD_BOOTLOADER_CMD_W                                0xE6
#define CMD_DATA_R                                          0xE7

//#define CMD_MFR_C1_C2_ARA_CONFIG                          0xE0
//#define CMD_MFR_C2_LOGIC                                  0xE1
//#define CMD_MFR_PGOOD_POLARITY                            0xE2
//#define CMD_RESERVED_E3                                   0xE3
//#define CMD_RESERVED_E4                                   0xE4
//#define CMD_RESERVED_E5                                   0xE5
//#define CMD_RESERVED_E6                                   0xE6
//#define CMD_RESERVED_E7                                   0xE7
#define CMD_MFR_COMCODE                                     0xE8
//#define CMD_RESERVED_E9                                   0xE9
//#define CMD_RESERVED_EA                                   0xEA
//#define CMD_RESERVED_EB                                   0xEB
//#define CMD_RESERVED_EC                                   0xEC
//#define CMD_RESERVED_ED                                   0xED
//#define CMD_RESERVED_EE                                   0xEE
//#define CMD_RESERVED_EF                                   0xEF
#define CMD_MFR_MOD_DATE_LOC_SN                             0xF0
//#define CMD_RESERVED_F1                                   0xF1
//#define CMD_RESERVED_F2                                   0xF2
//#define CMD_RESERVED_F3                                   0xF3
//#define CMD_RESERVED_F4                                   0xF4
//#define CMD_RESERVED_F5                                   0xF5
//#define CMD_RESERVED_F6                                   0xF6
//#define CMD_RESERVED_F7                                   0xF7
//#define CMD_RESERVED_F8                                   0xF8
//#define CMD_RESERVED_F9                                   0xF9
//#define CMD_RESERVED_FA                                   0xFA
//#define CMD_RESERVED_FB                                   0xFB
//#define CMD_RESERVED_FC                                   0xFC
//#define CMD_RESERVED_FD                                   0xFD
//#define CMD_RESERVED_FE                                   0xFE
#define UNSUPPORTED_CMD_CODE                                0xFF

#define CMD_MFR_PID_VBUCK		        0xEA
#define CMD_MFR_PID_VBOOST		        0xEB
#define CMD_MFR_PID_VBUCK_LOW_T         0xEC
#define CMD_MFR_PID_VBOOST_LOW_T        0xED
#define CMD_MFR_PID_IBUCK		        0xEE
#define CMD_MFR_PID_IBOOST		        0xEF

#define MFR_CMD_READ_DEBUG_BUF          0xF1
#define MFR_CMD_READ_ADC_ALL            0xF2
#define CMD_MFR_SET_VOUT                0xF8
#define CMD_MFR_SET_IOUT                0xF9


#endif

